export const FETCH_QUIZES_START = 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR',
    FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS',

    QUIZ_SUBMIT = 'QUIZ_SUBMIT',
    QUIZ_RETRY = 'QUIZ_RETRY',

    CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION',
    RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION',
    AUTH_SUCCESS = 'AUTH_SUCCESS',
    AUTH_LOGOUT = 'AUTH_LOGOUT';


